export const Images = Object.freeze({
    LoginLogo: require('../../assets/images/Logo.png'),
    icHeaderUser: require('../../assets/images/headerUser.png'),
    icFolder: require('../../assets/images/icFolder.png'),
    assigneMember: require('../../assets/images/assigneMember.png'),
    assigneMember2: require('../../assets/images/assigneMember2.png'),
    roundBackgroundImage: require('../../assets/images/roundBackgroundImage.png'),
    pdfImage: require('../../assets/images/pdfImage.png'),
    icPassword: require('../../assets/images/icPassword.png'),
    icEdit: require('../../assets/images/icEdit.png'),
    icNotification: require('../../assets/images/icNotification.png'),
    icAbout: require('../../assets/images/icAbout.png'),
    profileImage: require('../../assets/images/profileImage.png'),
    pdfSideBar: require('../../assets/images/pdfSideBar.png'),
    pdfFullScreen: require('../../assets/images/pdfFullScreen.png'),
    icMapImage: require('../../assets/images/icMapImage.png'),
    icUpload: require('../../assets/images/icUpload.png'),
    icUploadBulk: require('../../assets/images/icUploadBulk.png'),
    AddImagesGallery: require('../../assets/images/AddImagesGallery.png'),
    icPdfFile: require('../../assets/images/icPdfFile.png'),
    icAddImage: require('../../assets/images/icAddImage.png'),
})